### ISSUE TITLE
there are errors when run make.py

### ISSUE THREAD

**Issue by langhuihui** [mbebenita/Broadway#106]
4 warnings generated.
link -> avc.bc
C:/Program Files/Emscripten/clang/e1.35.0_64bit\llvm-link: D:\源码\Broadway\Decoder\obj\h264bsd_transform.o: error: Could not open input file: unknown error
0x00007FF7203F00D6 (0x000002806B693290 0x0000000000000030 0x000002806B840CC0 0x000002806B68F508)
0x00007FF7203D3E5B (0x000000000000001E 0x000000EA6FD8FBF0 0x000000EA6F27C000 0x000000EA6F27C000)
0x00007FF7203D4A29 (0x00007FF72052F88C 0x0000000000000000 0x00007FF72052F88C 0x00007FF72052F88C)
0x00007FF72052F82B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFF3D748102 (0x00007FFF3D7480E0 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x22 bytes(s)
0x00007FFF3DFAC2E4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x34 bytes(s)
Traceback (most recent call last):
  File "make.py", line 76, in <module>
    emscripten.Building.link(object_files, 'avc.bc')
  File "C:/Program Files/Emscripten/emscripten/1.35.0\tools\shared.py", line 1432, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error:

**Comment by soliton4** [comment]
i never tried running emscripten on an obscure operating system.
try running it on a unix based system. you should be fine

**Comment by langhuihui** [comment]
can i build avc.bc by myself?

**Comment by soliton4** [comment]
sure, the whole build process is automated

**Comment by langhuihui** [comment]
I means that  I need avc source code to build my own avc.bc. So where is avc source code?

**Comment by soliton4** [comment]
https://github.com/mbebenita/Broadway/tree/master/Decoder/src

**Comment by langhuihui** [comment]
in make.py line 75 ,it just uses the avc.bc. but which source code is avc's?

**Comment by soliton4** [comment]
see my post above @langhuihui

**Comment by langhuihui** [comment]
I don't understand.
https://github.com/mbebenita/Broadway/tree/master/Decoder/src
these codes just generate files below,there is no avc.bc
Decoder.o                    h264bsd_byte_stream.o
h264bsd_cavlc.o              h264bsd_conceal.o
h264bsd_deblocking.o         h264bsd_decoder.o
h264bsd_dpb.o                h264bsd_image.o
h264bsd_inter_prediction.o   h264bsd_intra_prediction.o
h264bsd_macroblock_layer.o   h264bsd_nal_unit.o
h264bsd_neighbour.o          h264bsd_pic_order_cnt.o
h264bsd_pic_param_set.o      h264bsd_reconstruct.o
h264bsd_seq_param_set.o      h264bsd_slice_data.o
h264bsd_slice_group_map.o    h264bsd_slice_header.o
h264bsd_storage.o            h264bsd_stream.o
h264bsd_transform.o          h264bsd_util.o
h264bsd_vlc.o                h264bsd_vui.o
H264SwDecApi.o

**Comment by soliton4** [comment]
just run the make.py. it will do all the build steps and copy the result into the player folder.

**Comment by langhuihui** [comment]
I know what your mean. I want to build the project on windows os. There are other projects to be built together. avc.bc seems be built on linux. So I can't link it

**Comment by soliton4** [comment]
i am perfectly happy to help you with any broadway.js related subjects or problems.
however i will not offer you windows support.

**Comment by langhuihui** [comment]
So I still don't know how to build avc.bc. Or where is the source code for it

**Comment by soliton4** [comment]
i am starting to suspect you are trolling me.

the source code is in the src folder

you build it by executing make.ph

```python make.py```

you need emscripten and python installed.

if you ask me again where the source code is i am not gonna answer.

**Comment by langhuihui** [comment]
do you mean make.py will generate avc.bc? I look into the make.py ,there is no script to do that thing.Only link the avc.bc.This file is already at https://github.com/mbebenita/Broadway/tree/master/Decoder

**Comment by soliton4** [comment]
yes. as far as i understand avc.bc is the result of the llvm linker.

**Comment by langhuihui** [comment]
I understand now.Thank you for your patience！
