### ISSUE TITLE
use emscripten run python make.py but error

### ISSUE THREAD

**Issue by a-jie** [mbebenita/Broadway#22]
undefined:60
    throw msg;
          ^
Assertion failed: asm.js heap must be power of 2
Traceback (most recent call last):
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/emscripten.py", line 860, in <module>
    _main(environ=os.environ)
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/emscripten.py", line 848, in _main
    temp_files.run_and_clean(lambda: main(
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/tools/tempfiles.py", line 38, in run_and_clean
    return func()
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/emscripten.py", line 856, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/emscripten.py", line 742, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/emscripten.py", line 184, in emscript
    assert '//FORWARDED_DATA:' in out, 'Did not receive forwarded data in pre output - process failed?'
AssertionError: Did not receive forwarded data in pre output - process failed?
Traceback (most recent call last):
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/emcc", line 1527, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/tools/shared.py", line 1159, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js: 
Traceback (most recent call last):
  File "make.py", line 77, in <module>
    emscripten.Building.emcc('avc.bc', emcc_args, os.path.join(JS_DIR, 'avc.js'))
  File "/Users/a-jie/Downloads/emsdk_portable/emscripten/1.5.6/tools/shared.py", line 1137, in emcc
    assert os.path.exists(output_filename), 'emcc could not create output file: ' + output_filename
AssertionError: emcc could not create output file: js/avc.js

**Comment by soliton4** [comment]
the latest emscripten should work
just compiled it - works like a charm
