### ISSUE TITLE
Error building with emscripten

### ISSUE THREAD

**Issue by samsamm777** [mbebenita/Broadway#48]
When running `$ python make.py ` i get the following errors...

```bash
emcc avc.bc -> js/avc.js
Traceback (most recent call last):
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/emscripten.py", line 1656, in <module>
    _main(environ=os.environ)
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/emscripten.py", line 1644, in _main
    temp_files.run_and_clean(lambda: main(
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/emscripten.py", line 1652, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/emscripten.py", line 1536, in main
    shared.Building.ensure_struct_info(struct_info)
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/tools/shared.py", line 1767, in ensure_struct_info
    gen_struct_info.main(['-qo', info_path, path_from_root('src/struct_info.json')])
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/tools/gen_struct_info.py", line 505, in main
    struct_info = inspect_code(header_files, cpp_opts, structs, defines)
  File "/mnt/nethome/users/joe.blogs/Downloads/emsdk_portable/emscripten/master/tools/gen_struct_info.py", line 380, in inspect_code
    info = subprocess.check_output([shared.LLVM_INTERPRETER, bin_file[1]]).splitlines()
AttributeError: 'module' object has no attribute 'check_output'
copying js/avc.js -> ../Player/avc-codec.js
```

Any ideas?

**Comment by samsamm777** [comment]
@mbebenita @bkw any ideas on this? im desperate to get this working, so i can use broadway in a worker thread

**Comment by samsamm777** [comment]
sussed this. You require python 2.7 to use the submodule.check_output. see: https://docs.python.org/2/library/subprocess.html
